### ISSUE TITLE
Put CSC logo and website on the review session

### ISSUE THREAD

**Issue by caltry** [caltry/CSC-reviews#16]

**Comment by caltry** [comment]
Hey @masterpi314,

Let me know if the change in c031fe2ad2149bd4d8a26d0fbf82ba74d1bef626 is something along the lines of what you're looking for.

**Comment by masterpi314** [comment]
How does this look for adding the logo as well? 

https://github.com/masterpi314/CSC-reviews/commit/ee2ec8d8aff70cfc5b5ba7bfed56d18b158aca40

**Comment by caltry** [comment]
I like that!

Will it still look ok when printed in greyscale?

We should put the logo higher in the tree (perhaps /include) so that we can share it between all of the reviews.

**Comment by masterpi314** [comment]
I'm not sure.  We could make a black and white version as well and put switching logic in the macro.

**Comment by caltry** [comment]
I'll print out the first page in time for the Monday meeting, and we can take a look at it there.

`make realclean' currently deletes the logo. I'm guessing that you put it in as a PDF so that it could remain as a vector graphic?

**Comment by masterpi314** [comment]
Yep.  PDF is the easiest format to use for vector graphics with pdflatex.  We can put it in a directory for just graphics or somesuch.  It should really be moved to a more global location anyway.

**Comment by caltry** [comment]
Oh, right, if we end up moving the logo to a more global include dir,
it won't get deleted by 'realclean' anyways.

**Comment by caltry** [comment]
Adam, please give me a pull request when you move the logo to /include on your repo.

**Comment by caltry** [comment]
Fixed (by Adam) in f17e2ae0a1868b381564a8d320a05b2f6ffd08f1
