### ISSUE TITLE
241 .split()

### ISSUE THREAD

**Issue by hcwndbyw** [caltry/CSC-reviews#3]
241 Students don't know about lists or split. Some questions will have to be reworked. BAH.
I think question 3 will be fine if we make sure its one work per line.
Question 5, if we give a string and have them return the sum of the digits would be okay I think.

**Comment by caltry** [comment]
What's currently the problem with question 5? Is it the lists?

**Comment by caltry** [comment]
[master 764bdad] Remove String.split() from question 3.

But this makes me think... can the solution just involve checking for white-space to determine where words begin and end?

**Comment by caltry** [comment]
Oh, also: for question 5, are the students familiar with int() and str()?

**Comment by caltry** [comment]
Please check out:
[master 65e9174] Replace question 2, which required slicing.

Which should fix the problem with  question 2. It's a bit heavy on knowledge of string slicing; let me know if it needs to be modified.

**Comment by hcwndbyw** [comment]
Alright I haven't changed anything yet, but here are my thoughts:

For question 5, the students know int(), but I'm not sure about str(). I'll work that out.

I like the new question 2 and I think its right on par. Perhaps change the wording? Saying it folds around a point n or something to that end might be more clear but I'm not sure.

We can do whitespace for question 3, but I think the current way is fine.
