### ISSUE TITLE
New 241 question too hard?

### ISSUE THREAD

**Issue by hcwndbyw** [caltry/CSC-reviews#6]
I added a question but I'm not sure if its too difficult. Check it out when you get a chance?

**Comment by caltry** [comment]
I think that you should remove the condition "If the length of the compressed string is longer than the original string, return the original string." It somehow just seems like weird behavior for a compression function, and may complicate things. Without that clause, for example, we can safely include numbers in our input strings and still be able to implement a simple decompression function. It's really not a /big/ deal though, and if you included it for a specific reason, we should leave it in.

I suppose I might say that this is on the challenging side, here's my solution for your reference:

```
compress( string ):
    if len(string) < 1:
        return string

    current_char    = string[0]
    frequency       = 1
    output_string   = ""
    i = 1
    while i < len(string):
        if string[i] == current_char:
            frequency += 1
        else:
            output_string += current_char + str(frequency)
            current_char = string[i]
            frequency = 1

    if len(string) < len(output_string):
        return string
    else:
        return output_string
```

I think that your solution is too complicated for their level: a nested loop that modifies the invariant of the outer loop could be confusing, especially for students struggling to understand scope rules.

I do like the idea, though (and it gives me a good idea for a 242 problem!). I think it's fine as-is, but if other reviewers feel that it's too tough, we can ask them to implement decompress(), which has a simpler implementation.

**Comment by hcwndbyw** [comment]
I got rid of the length thing at the end. I can also see how my solution might be too complicated. Feel free to modify it if you want to use your solution. 

Also, I think my 242 stack question may be too difficult. Let me know.

Who are we having review these???

**Comment by caltry** [comment]
```
I think my 242 stack question may be too difficult. Let me know.
```

Nope, I think it's fine.

```
Who are we having review these??? 
```

Hopefully someone. Mike or Chris or Matt, I hope.

**Comment by hcwndbyw** [comment]
I also will try to get a few professors to review them. I'll be working with  Nunes-Harwitt tomorrow morning, and perhaps he will look at it. I'll also harass prof White (who has the all the 241 sections).

**Comment by hcwndbyw** [comment]
Nunes-Harwitt looked over the 242 review and  thought it was reasonable.

**Comment by hcwndbyw** [comment]
I think everything is okay now. Prof White liked what he saw.
